spring:
   datasource:
       driver-class-name: org.h2.Driver
       url: jdbc:h2:file:~/h2/web-simona;DB_CLOSE_ON_EXIT=TRUE
       username: sa
       password:
   jpa:
#       generate-ddl: true
       hibernate:
           ddl-auto: create
       properties:
            hibernate:
              dialect: org.hibernate.dialect.H2Dialect

liquibase:
    change-log: classpath:db/liquibase-changelog.xml